# Generated by Django 6.0.3 on 2026-03-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_userid_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.country'),
        ),
    ]
